import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthService } from '../../../core/services/auth.service';
import { PayrollService } from '../../../core/services/payroll.service';
import { Payslip } from '../../../core/models/payroll.model';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'app-payroll-list',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <div class="page-header">
      <h2>Payslips</h2>
      
      <!-- Generate Section (HR/Admin only) -->
      <div *ngIf="canGenerate" class="generate-box">
         <form [formGroup]="generateForm" (ngSubmit)="onGenerate()" class="inline-form">
           <div class="input-group">
             <label>Period</label>
             <input type="month" formControlName="payPeriod" class="form-control">
           </div>
           <div class="input-group">
             <label>Emp ID</label>
             <input type="number" formControlName="employeeId" placeholder="ID" class="form-control" style="width: 100px;">
           </div>
           <button type="submit" [disabled]="generating || generateForm.invalid" class="btn-primary">
             {{ generating ? 'Generating...' : 'Generate New' }}
           </button>
         </form>
         <span *ngIf="error" class="error-msg">{{ error }}</span>
         <span *ngIf="successMsg" class="success-msg">{{ successMsg }}</span>
      </div>
    </div>

    <div class="table-container">
      <table class="data-table">
        <thead>
          <tr>
            <th>Pay Period</th>
            <th>Base Salary</th>
            <th>Bonuses</th>
            <th>Leave Deduct</th>
            <th>Tax</th>
            <th>Net Salary</th>
            <th>Generated By</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let slip of payslips">
            <td class="period-cell">{{ slip.payPeriod }}</td>
            <td>{{ slip.baseSalary | currency:'USD' }}</td>
            <td class="positive">+{{ slip.totalBonuses | currency:'USD' }}</td>
            <td class="negative">-{{ slip.unpaidLeaveDeduction | currency:'USD' }}</td>
            <td class="negative">-{{ slip.taxAmount | currency:'USD' }}</td>
            <td class="net-salary">{{ slip.netSalary | currency:'USD' }}</td>
            <td>User {{ slip.generatedBy }}</td>
          </tr>
          <tr *ngIf="payslips.length === 0">
            <td colspan="7" class="empty-state">No payslips found</td>
          </tr>
        </tbody>
      </table>
    </div>
  `,
  styles: [`
    .page-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 2rem; }
    .generate-box { background: var(--surface-color); padding: 1rem; border-radius: 8px; border: 1px solid var(--border-color); }
    .inline-form { display: flex; gap: 1rem; align-items: flex-end; }
    .input-group { display: flex; flex-direction: column; gap: 0.25rem; }
    .input-group label { font-size: 0.75rem; color: var(--text-secondary); }
    .form-control { padding: 0.5rem; border: 1px solid var(--border-color); border-radius: 4px; }
    .btn-primary { background: var(--primary-color); color: white; border: none; padding: 0.6rem 1rem; border-radius: 4px; cursor: pointer; height: 38px; }
    .btn-primary:disabled { opacity: 0.7; }
    .table-container { background: var(--surface-color); border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); overflow: hidden; }
    .data-table { width: 100%; border-collapse: collapse; }
    .data-table th, .data-table td { padding: 1rem; text-align: right; border-bottom: 1px solid var(--border-color); }
    .data-table th:first-child, .data-table td:first-child { text-align: left; }
    .data-table th:last-child, .data-table td:last-child { text-align: center; }
    .period-cell { font-weight: 600; color: var(--text-primary); }
    .positive { color: var(--success-color); }
    .negative { color: var(--error-color); }
    .net-salary { font-weight: 700; color: var(--primary-color); }
    .error-msg { color: var(--error-color); font-size: 0.8rem; display: block; margin-top: 0.5rem; }
    .success-msg { color: var(--success-color); font-size: 0.8rem; display: block; margin-top: 0.5rem; }
    .empty-state { text-align: center; color: var(--text-secondary); padding: 2rem; }
  `]
})
export class PayrollListComponent implements OnInit {
  payslips: Payslip[] = [];
  generateForm: FormGroup;
  canGenerate = false;
  generating = false;
  error = '';
  successMsg = '';
  currentEmployeeId: number | null = null;
  currentUserId: number = 0;

  constructor(
    private payrollService: PayrollService,
    private authService: AuthService,
    private fb: FormBuilder,
    private cdr: ChangeDetectorRef
  ) {
    this.generateForm = this.fb.group({
      payPeriod: ['', Validators.required],
      employeeId: ['', Validators.required]
    });
  }

  ngOnInit() {
    const user = this.authService.currentUser();
    if (user) {
      this.currentUserId = user.userId;
      this.currentEmployeeId = user.employeeId || null;
      this.canGenerate = ['HR', 'ADMIN'].includes(user.role);

      // Fetch payslips for the logged-in employee to see their own history
      if (this.currentEmployeeId) {
        this.loadPayslips();
      }
    }
  }

  loadPayslips() {
    if (!this.currentEmployeeId) return;
    this.payrollService.getMyPayslips(this.currentEmployeeId).subscribe({
      next: (data) => {
        this.payslips = data;
        this.cdr.detectChanges();
      }
    });
  }

  onGenerate() {
    if (this.generateForm.invalid) return;

    this.generating = true;
    this.error = '';
    this.successMsg = '';

    const req = {
      employeeId: this.generateForm.value.employeeId,
      payPeriod: this.generateForm.value.payPeriod
    };

    this.payrollService.generatePayslip(req)
      .pipe(finalize(() => {
        this.generating = false;
        this.cdr.detectChanges();
      }))
      .subscribe({
        next: (slip) => {
          this.successMsg = 'Payslip Generated Successfully!';
          // If generated for self, add to list
          if (this.currentEmployeeId && req.employeeId == this.currentEmployeeId) {
            this.payslips.unshift(slip);
          }
          this.generateForm.reset();
        },
        error: (err) => {
          const msg = typeof err.error === 'string' ? err.error : 'Failed to generate payslip.';
          this.error = msg;
        }
      });
  }
}
